apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: zhangtianxu/live-streaming-vue:v0.03
        ports:
        - containerPort: 80
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: nginx-service-80-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: nginx-service-8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081

