spring:
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板
  main:
    allow-bean-definition-overriding: true


server:
  port: 8082


mybatis-plus:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
    - classpath*:mapper/*.xml
  global-config:
    db-config:
      table-underline: true
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# 自定义类 ignoreConfig，URL 的白名单
secure:
  ignored:
    urls: #安全路径白名单
      - /doc.html
      - /swagger-ui/**
      - /swagger/**
      - /swagger-resources/**
      - /**/v3/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /users/login
      - /users/sendMailCode
      - /users/registerByMail
      - /users/info
      - /users/logout
      - /minio/upload
      - /live_callback/**
      - /storage/**
      - /live/get_all_types
      - /live/get_all_online_rooms
      - /live/get_room_by_type
      - /live/get_rooms_on_top
      - /live//get_recording
      - /live/get_room_state
      - /friendship/get_followed_counts
      - /live/get_room_by_username
      - /users/get_user_info_by_id_or_name


# 登录认证 token filter
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: codingmore-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头


recording:
  minTime: 5 #直播历史最短时间，默认5分钟